num_multimask_outputs:
  3
transformer_dim:
  256
iou_head_depth:
  3
iou_head_hidden_dim:
  256
encoder_embedding_dim:
  1280
transformer:
  depth:
    2
  embedding_dim:
    256
  mlp_dim:
    2048
  num_heads:
    8