continue_learning:
  named:
    "bdd10k"
  located:
    "暂时不明"
  class_number:
    18
  classes_name:
    "classes/bdd10k.txt"
  training:
    task_1:
      training_type:
        "none"
      design:
        "none"
      index_order:
        "none"
    task_2:
      training_type:
        "none"
      design:
        "none"
      index_order:
        "none"