name:
  "VOC"
class_number:
  20
training:
  #you and add your task as task_3 and so on
  task_1:
    training_type:
      "overlapped"
    design:
      "18-2"
    index_order:
      "default"
evaluate:
  task_1:
    type:
      ["only stage","all"]
dataset_setting:
  root:
    "PascalVOC12"
  classes:
    "default"
  need_index_name:
    True
  ignore_index:
    [0,255]
increment_setting:
  segmentation_dataset_name:
    "default"
  #default is name.Segmentation
  segmentation_config:
    "default"
  overlap:
    True
  masking:
    True
  data_masking:
    "current"
  #current or current+old or all
  no_memory:
    True
  new_image_path:
    "path"
  save_stage_image_list_path:
    "default"